"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/CSVQuickEdit.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'assets/csv.icns',
    'packages': ['PyQt5'],  # Ensures PyQt5 is included
    'argv_emulation': True,  # Handles command-line arguments properly
    'includes': ['sip'],  # Includes SIP module, which PyQt5 depends on
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
